<a href="https://colab.research.google.com/github/SeokhunEom/DeepLearning-study/blob/main/Section_6_Softmax_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf  # Import TensorFlow library
import numpy as np  # Import NumPy library for array manipulation

In [2]:
# Raw input data for features (X) and labels (Y)
x_raw = [[1, 2, 1, 1],
         [2, 1, 3, 2],
         [3, 1, 3, 4],
         [4, 1, 5, 5],
         [1, 7, 5, 5],
         [1, 2, 5, 6],
         [1, 6, 6, 6],
         [1, 7, 7, 7]]

y_raw = [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1],
         [0, 1, 0],
         [0, 1, 0],
         [0, 1, 0],
         [1, 0, 0],
         [1, 0, 0]]

In [3]:
# Convert raw data to NumPy arrays with type float32
x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

In [4]:
# Define the number of classes for the output layer
nb_classes = 3

In [5]:
# Create a Sequential model
tf.model = tf.keras.Sequential()

In [6]:
# Add a Dense layer with 4 input dimensions and 'nb_classes' units (output neurons)
# use_bias=True is the default setting to include a bias term in the computation
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))

In [7]:
# Add a Softmax activation layer to normalize the output into a probability distribution
tf.model.add(tf.keras.layers.Activation('softmax'))

In [8]:
# Compile the model
# - loss: categorical cross-entropy for multi-class classification
# - optimizer: Stochastic Gradient Descent (SGD) with learning rate 0.1
# - metrics: accuracy to monitor during training
tf.model.compile(loss='categorical_crossentropy',
                 optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
                 metrics=['accuracy'])

In [9]:
# Print the model summary to show the layers and parameters
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
 activation (Activation)     (None, 3)                 0         
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
# Train the model with the training data
# - epochs: number of iterations over the entire dataset
history = tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 1s 809ms/step - loss: 2.3109 - accuracy: 0.1250
Epoch 2/2000
1/1 [==============================] - 0s 23ms/step - loss: 1.8493 - accuracy: 0.1250
Epoch 3/2000
1/1 [==============================] - 0s 24ms/step - loss: 1.6101 - accuracy: 0.1250
Epoch 4/2000
1/1 [==============================] - 0s 14ms/step - loss: 1.5020 - accuracy: 0.2500
Epoch 5/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.4341 - accuracy: 0.2500
Epoch 6/2000
1/1 [==============================] - 0s 20ms/step - loss: 1.4000 - accuracy: 0.2500
Epoch 7/2000
1/1 [==============================] - 0s 21ms/step - loss: 1.4054 - accuracy: 0.2500
Epoch 8/2000
1/1 [==============================] - 0s 13ms/step - loss: 1.3934 - accuracy: 0.2500
Epoch 9/2000
1/1 [==============================] - 0s 22ms/step - loss: 1.3819 - accuracy: 0.2500
Epoch 10/2000
1/1 [==============================] - 0s 14ms/step - loss: 1.3419 - accuracy: 0.2500
Epoch 11

In [11]:
# Make a prediction with new input data and print the result
# Using a sample input [[1, 11, 7, 9]]
a = tf.model.predict(np.array([[1, 11, 7, 9]]))

# Print the prediction probabilities and the class with the highest probability
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

1/1 [==============================] - 0s 183ms/step
[[1.11749945e-02 9.88814533e-01 1.04403707e-05]] [1]


In [12]:
# Make another prediction with a different input [[1, 3, 4, 3]]
b = tf.model.predict(np.array([[1, 3, 4, 3]]))

# Print the prediction probabilities and the class with the highest probability
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

1/1 [==============================] - 0s 41ms/step
[[0.7960381  0.18221393 0.02174798]] [0]


In [13]:
# Make a prediction with yet another input [[1, 1, 0, 1]]
c = tf.model.predict(np.array([[1, 1, 0, 1]]))

# Convert the prediction probabilities to one-hot encoded format
c_onehot = np.argmax(c, axis=-1)

# Print the prediction probabilities and the one-hot encoded result
print(c, c_onehot)

1/1 [==============================] - 0s 46ms/step
[[1.7149809e-08 3.7925021e-04 9.9962068e-01]] [2]


In [14]:
# Make predictions for multiple inputs at once
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))

# Convert all prediction probabilities to one-hot encoded format
all_onehot = np.argmax(all, axis=-1)

# Print all prediction probabilities and their one-hot encoded results
print(all, all_onehot)

1/1 [==============================] - 0s 29ms/step
[[1.1175006e-02 9.8881453e-01 1.0440382e-05]
 [7.9603809e-01 1.8221393e-01 2.1747988e-02]
 [1.7149809e-08 3.7925021e-04 9.9962068e-01]] [1 0 2]


In [15]:
import tensorflow as tf  # Import TensorFlow library
import numpy as np  # Import NumPy library for array manipulation

# Set random seed for reproducibility
tf.random.set_seed(777)

# Input data for features (X) and labels (Y)
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Convert data to NumPy arrays with float32 type
x_data = np.array(x_data, dtype=np.float32)
y_data = np.array(y_data, dtype=np.float32)

# Define the number of classes for the output layer
nb_classes = 3

# Create a Sequential model
model = tf.keras.Sequential()

# Add a Dense layer with 4 input dimensions and 'nb_classes' units (output neurons)
model.add(tf.keras.layers.Dense(units=nb_classes, input_shape=(4,), use_bias=True))

# Add a Softmax activation layer to normalize the output into a probability distribution
model.add(tf.keras.layers.Activation('softmax'))

# Compile the model
# - loss: categorical cross-entropy for multi-class classification
# - optimizer: Stochastic Gradient Descent (SGD) with learning rate 0.1
# - metrics: accuracy to monitor during training
model.compile(loss='categorical_crossentropy',
              optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
              metrics=['accuracy'])

# Print the model summary to show the layers and parameters
model.summary()

# Train the model with the training data
# - epochs: number of iterations over the entire dataset
history = model.fit(x_data, y_data, epochs=2001)

# Separator for clarity in the output
print('--------------')

# Make a prediction with new input data and print the result
# Using a sample input [[1, 11, 7, 9]]
a = model.predict(np.array([[1, 11, 7, 9]], dtype=np.float32))

# Print the prediction probabilities and the class with the highest probability
print(a, np.argmax(a, axis=1))

print('--------------')

# Make another prediction with a different input [[1, 3, 4, 3]]
b = model.predict(np.array([[1, 3, 4, 3]], dtype=np.float32))

# Print the prediction probabilities and the class with the highest probability
print(b, np.argmax(b, axis=1))

print('--------------')

# Make a prediction with yet another input [[1, 1, 0, 1]]
c = model.predict(np.array([[1, 1, 0, 1]], dtype=np.float32))

# Print the prediction probabilities and the class with the highest probability
print(c, np.argmax(c, axis=1))

print('--------------')

# Make predictions for multiple inputs at once
all_predictions = model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]], dtype=np.float32))

# Print all prediction probabilities and their one-hot encoded results
print(all_predictions, np.argmax(all_predictions, axis=1))


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 3)                 15        
                                                                 
 activation_1 (Activation)   (None, 3)                 0         
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/2001
1/1 [==============================] - 1s 558ms/step - loss: 3.1803 - accuracy: 0.3750
Epoch 2/2001
1/1 [==============================] - 0s 15ms/step - loss: 1.4439 - accuracy: 0.2500
Epoch 3/2001
1/1 [==============================] - 0s 12ms/step - loss: 1.0778 - accuracy: 0.3750
Epoch 4/2001
1/1 [==============================] - 0s 16ms/step - loss: 1.1299 - accuracy: 0.6250
Epoch 5/2001
1/1 [=