<a href="https://colab.research.google.com/github/SeokhunEom/DeepLearning-study/blob/main/Section_8_Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Migrate from TensorFlow 1.x to TensorFlow 2 by ChatGPT
import tensorflow as tf
import numpy as np
import pprint

In [2]:
# Setting the seed for reproducibility
tf.random.set_seed(777)

# Pretty printer for displaying the numpy arrays
pp = pprint.PrettyPrinter(indent=4)

In [3]:
# TensorFlow 2.x uses eager execution by default, so no need for tf.InteractiveSession()

# Creating a numpy array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)  # Pretty print the array
print(t.ndim)  # Print the number of dimensions (rank) of the array
print(t.shape)  # Print the shape of the array
print(t[0], t[1], t[-1])  # Accessing elements by index
print(t[2:5], t[4:-1])  # Slicing the array
print(t[:2], t[3:])  # Slicing the array

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [4]:
# Creating a 2D numpy array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)  # Print the number of dimensions (rank)
print(t.shape)  # Print the shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [5]:
# Creating TensorFlow constants
t = tf.constant([1, 2, 3, 4])
print(tf.shape(t))  # Print the shape of the tensor

tf.Tensor([4], shape=(1,), dtype=int32)


In [6]:
t = tf.constant([[1, 2],
                 [3, 4]])
print(tf.shape(t))  # Print the shape of the tensor

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [7]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(tf.shape(t))  # Print the shape of the tensor

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [8]:
# Creating a nested list structure
nested_list = [
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]
        ],
        [
            [13, 14, 15, 16],
            [17, 18, 19, 20],
            [21, 22, 23, 24]
        ]
    ]
]

In [9]:
# Matrix multiplication
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
print(tf.linalg.matmul(matrix1, matrix2))  # Matrix multiplication

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


In [10]:
# Element-wise multiplication
print(matrix1 * matrix2)

tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


In [11]:
# Addition of matrices
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
print(matrix1 + matrix2)

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
print(matrix1 + matrix2)

tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor([[5. 5.]], shape=(1, 2), dtype=float32)


In [12]:
# Generating random numbers
print(tf.random.normal([3]))  # Random normal distribution
print(tf.random.uniform([2]))  # Random uniform distribution
print(tf.random.uniform([2, 3]))  # Random uniform distribution with shape [2, 3]

tf.Tensor([ 0.7706481   0.37335402 -0.05576323], shape=(3,), dtype=float32)
tf.Tensor([0.42134905 0.7339295 ], shape=(2,), dtype=float32)
tf.Tensor(
[[0.909613   0.34968376 0.39626384]
 [0.6574153  0.60619414 0.70691717]], shape=(2, 3), dtype=float32)


In [13]:
# Reductions
print(tf.reduce_mean([1, 2], axis=0))  # Mean reduction
x = [[1., 2.],
     [3., 4.]]
print(tf.reduce_mean(x))  # Mean of all elements
print(tf.reduce_mean(x, axis=0))  # Mean along the first axis
print(tf.reduce_mean(x, axis=1))  # Mean along the second axis
print(tf.reduce_mean(x, axis=-1))  # Mean along the last axis
print(tf.reduce_sum(x))  # Sum of all elements
print(tf.reduce_sum(x, axis=0))  # Sum along the first axis
print(tf.reduce_sum(x, axis=-1))  # Sum along the last axis
print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)))  # Mean of the sums along the last axis

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)


In [14]:
# Argmax
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0))  # Argmax along the first axis
print(tf.argmax(x, axis=1))  # Argmax along the second axis
print(tf.argmax(x, axis=-1))  # Argmax along the last axis

tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)


In [15]:
# Reshaping tensors
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
print(t.shape)  # Shape of the numpy array
print(tf.reshape(t, shape=[-1, 3]))  # Reshape to a different shape
print(tf.reshape(t, shape=[-1, 1, 3]))  # Reshape to a different shape

(2, 2, 3)
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int64)
tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int64)


In [16]:
# Squeezing and expanding dimensions
print(tf.squeeze([[0], [1], [2]]))  # Remove dimensions of size 1
print(tf.expand_dims([0, 1, 2], 1))  # Add a dimension

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


In [17]:
# One-hot encoding
print(tf.one_hot([[0], [1], [2], [0]], depth=3))  # One-hot encode with a specified depth
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(tf.reshape(t, shape=[-1, 3]))  # Reshape the one-hot encoded tensor

tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]], shape=(4, 3), dtype=float32)


In [18]:
# Casting types
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))  # Cast to int32
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))  # Cast boolean to int32

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


In [19]:
# Stacking arrays
x = [1, 4]
y = [2, 5]
z = [3, 6]
print(tf.stack([x, y, z]))  # Stack along the first dimension
print(tf.stack([x, y, z], axis=1))  # Stack along a specified axis

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [20]:
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.ones_like(x))  # Create a tensor of ones with the same shape as x
print(tf.zeros_like(x))  # Create a tensor of zeros with the same shape as x

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [21]:
# Using Python's zip function
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9


In [22]:
# Transposing tensors
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)  # Print shape
pp.pprint(t)  # Pretty print the array

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [23]:
# Transpose the tensor
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

t = tf.transpose(t1, [1, 0, 2])
pp.pprint(t.shape)
pp.pprint(t)

t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(t2.shape)
pp.pprint(t2)

t = tf.transpose(t2, [2, 0, 1])
pp.pprint(t.shape)
pp.pprint(t)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])>
TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>
TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])>
TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>
